# Generated by Django 4.2.2 on 2023-06-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data',
            new_name='data_of_created',
        ),
    ]
